### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by mcanonic** [google/adb-sync#26]
Hi,
I've wrote a dummy app that creates files. With adb-sync I would try to keep track of change on the files creates. But the following command:

./adb-sync --dry-run --emulator --reverse /data/user/0/com.example.mex.dummyapp/files ./backup/
I got this permission denied error:
Sync: local ./backup//files, remote /data/user/0/com.example.mex.dummyapp/files
Scanning and diffing...
ls: /data/user/0/com.example.mex.dummyapp/files: Permission denied
No files seen. User error?
Total: 0 bytes

How can I fix this issue? 

Thanks,
M

**Comment by mcanonic** [comment]
My bad: I had to run
adb root 
M

**Comment by divVerent** [comment]
Yeah, that's probably the only thing we can do for now.
