### ISSUE TITLE
Hard-coded location of python3

### ISSUE THREAD

**Issue by duncan-bayne** [google/adb-sync#35]
The scripts assume that the python3 binary is located in `/usr/bin/python3`.  This is true of most GNU/Linux distributions, but not other OSs (notably FreeBSD, which I use).

**Comment by duncan-bayne** [comment]
Ah, this seems to be fixed by https://github.com/google/adb-sync/pull/32.  If @jottr doesn't sign the CLA soon, I'll submit my own PR from https://github.com/duncan-bayne/adb-sync/tree/use-env-35.

**Comment by divVerent** [comment]
Yes, thanks to both of you!
