### ISSUE TITLE
Use my fork

### ISSUE THREAD

**Issue by SelfAdjointOperator** [google/adb-sync#58]
Hi everyone. I recently rewrote this script from scratch (check out my fork). It was much easier to create anew instead of salvaging the awful code format and Python2-ish syntax from here, and the diffing function for excluded files required a nontrivial rewrite.

It has `--exclude`, `--exclude-from`, `--delete-exluded` options.

I have tried this extensively on Linux and it's great. Let me know if there's any path joining issues on Windows, though I think I've covered them all. I'm not too bothered about a pull request as long as people know about this. Enjoy!

**Comment by divVerent** [comment]
I do not think I will merge this rewrite - it's too big a change to do at once.

However - do you want to just keep the rewrite and I mark this project obsolete in README and link to your project? If you want to do that, let's go for it.

**Comment by SelfAdjointOperator** [comment]
> I do not think I will merge this rewrite - it's too big a change to do at once.
> 
> However - do you want to just keep the rewrite and I mark this project obsolete in README and link to your project? If you want to do that, let's go for it.

That sounds great!

**Comment by gnufred** [comment]
@divVerent Can you please procee? The current scripts has issues with symlinks that the fork fixed. I would have save me a lot of time if the README.md had the deprecation notice and the link to @SelfAdjointOperator 's fork :)

**Comment by divVerent** [comment]
Done that.

Long-term I also want to replace the entire project by something that uses `adb-channel` (already here) and uploads one or two small binaries to the phone and runs them there.

Probably more portable than trying to parse `ls` output that varies between devices.
